baseURL       = "https://curioo.city"
languageCode  = "en-us"
title         = "curiOOcity"
theme         = "curioocity"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Explore"
    url     = "explore"
    weight  = 1
  [[menu.nav]]
    name    = "Guide"
    url     = "guide"
    weight  = 2
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 3

# Site Params
[params]
  logo = "images/logo.png"
  logo_footer = "images/logo-footer.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "curiOOcity Web | Designed by SaasHup"
  author = "SaasHup"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = ""

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Question Type"
    placeholder_about_the_project = "Describe your question"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Guide"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Explore"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Walk, play and discover the world"
    tagline               = "You explore, You guide"
    primary_button        = "Explore"
    primary_button_url    = "explore"
    secondary_button      = "Guide"
    secondary_button_url  = "guide"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "OUR BEST GUIDES"
    subtitle  = "Crafting Hunts and seeking to make the walks fun and unique."
    #view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "PLAY"
    primary_button      = "Android"
    primary_button_url  = "https://play.google.com/store/games?"
    secondary_button    = "Apple"
    secondary_button_url = "https://www.apple.com/fr/app-store/"
    third_button      = "Web"
    third_button_url  = "https://app.curioo.city"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "4ter rue Robert Schuman, Saint-privat-la-montagne"
      phone   = "+3312345678"
      email   = "info@curioo.city"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Explore"
          url  = "explore"
        [[params.footer.sitemap.link]]
          name = "Guide"
          url  = "guide"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "#"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Github"
          url  = "#"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "#"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "About"
        description = "Walk, play and discover the world"
      [params.footer.back_to_top]
        description = "I want to <br> visit again"
