baseURL = 'https://curioo.city/'
title = 'CuriOO.city'
sectionPagesMenu = 'main'
disableKinds = ['taxonomy', 'term']

defaultContentLanguage = 'fr'
[languages]
  [languages.fr]
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
    weight = 1
  [languages.en]
    disabled = false
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true

