# theme.toml template for a Hugo theme
name = "Curioocity"
license = "MIT"
licenselink = "https://github.com/Saashup"
description = "CuriooCity Website"
homepage = "https://saashup.com/"
tags = ['clean', 'minimal']
features = ['landing-page', 'minimal']
min_version = "0.58.0"

[author]
  name = "SaasHup"
  homepage = "https://saashup.com/"
